# Generated by Django 5.1.2 on 2025-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignedprojects',
            fields=[
                ('pid', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('student_email_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('deadline_date', models.DateField()),
            ],
            options={
                'db_table': 'Assignedprojects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('email_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Professors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requestform',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Requestform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('email_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submittedprojects',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('feedback', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Submittedprojects',
                'managed': False,
            },
        ),
    ]
