# Generated by Django 5.1.2 on 2025-03-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedprojects',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='professors',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='requestform',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='submittedprojects',
            options={'managed': True},
        ),
    ]
