# Generated by Django 5.1.2 on 2025-03-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_assignedprojects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedprojects',
            name='professor_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.professors'),
        ),
        migrations.AddField(
            model_name='assignedprojects',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='professor_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.professors'),
        ),
        migrations.AddField(
            model_name='requestform',
            name='project_name',
            field=models.ForeignKey(blank=True, db_column='project_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.projects'),
        ),
        migrations.AddField(
            model_name='requestform',
            name='student_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.students'),
        ),
        migrations.AddField(
            model_name='submittedprojects',
            name='assigned_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.assignedprojects'),
        ),
        migrations.AddField(
            model_name='submittedprojects',
            name='professor_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.professors'),
        ),
        migrations.AddField(
            model_name='submittedprojects',
            name='project_name',
            field=models.ForeignKey(blank=True, db_column='project_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.projects'),
        ),
        migrations.AddField(
            model_name='submittedprojects',
            name='student_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.students'),
        ),
    ]
