# Generated by Django 5.1.2 on 2025-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_assignedprojects_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedprojects',
            name='student_email_id',
            field=models.CharField(max_length=255),
        ),
    ]
