# Generated by Django 5.1.2 on 2025-03-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_assignedprojects_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedprojects',
            name='student_email_id',
            field=models.ForeignKey(db_column='student_email_id', on_delete=django.db.models.deletion.CASCADE, to='home.students'),
        ),
    ]
