# Generated by Django 5.1.2 on 2025-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_assignedprojects_student_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedprojects',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
