# Generated by Django 5.1.2 on 2025-03-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_submittedprojects_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedprojects',
            name='file',
        ),
    ]
