# Generated by Django 5.1.2 on 2025-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_submittedprojects_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedprojects',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
