# Generated by Django 5.1.2 on 2025-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_submittedprojects_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedprojects',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
