# Generated by Django 5.1.2 on 2025-03-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_assignedprojects_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedprojects',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projects'),
        ),
    ]
