# Generated by Django 5.1.2 on 2025-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_assignedprojects_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedprojects',
            name='meeting_time',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, null=True),
        ),
    ]
