# Generated by Django 5.1.2 on 2025-03-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_assignedprojects_meeting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorMeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_meeting_time', models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, null=True)),
                ('professor_email', models.ForeignKey(db_column='professor_email', on_delete=django.db.models.deletion.CASCADE, to='home.professors')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projects')),
            ],
            options={
                'db_table': 'ProfessorMeetingSchedule',
                'managed': True,
            },
        ),
    ]
