# Generated by Django 5.2 on 2025-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_professormeetingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='github_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
