# Generated by Django 5.2 on 2025-05-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_submittedprojects_github_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedprojects',
            name='github_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
